### ISSUE TITLE
Card Infinite Spites

### ISSUE THREAD

**Issue by lumisapps** [lobbienjonsji/T.E.A.#6]
When playing the power card Infinite Spite throws error with "File not found: tea\img\powers\spits.png (Internal)", causing the crash of Slay the Spire.

Side note: congratulations for the mod, it's very interesting!

**Comment by lobbienjonsji** [comment]
I will look into it

**Comment by lobbienjonsji** [comment]
Ok the error is fxed and the new version of the mod is up. Enjoy :)
